In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('../resources/datasets/Airbnb_Open_Data.csv', low_memory=False)

In [4]:
data.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [6]:
data.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [7]:
data.tail(30)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
102569,6078630,"Elegant 1BR, Private Bath in Brownstone",37385825013,verified,Emily And Joel,Brooklyn,Park Slope,40.66880,-73.97865,United States,...,$197,1.0,184.0,2/10/2019,3.86,4.0,4.0,407.0,NO Smoking,NaN
102570,6079182,park slope duplex with yard,18572370488,verified,Liz,Brooklyn,Park Slope,40.67792,-73.98035,United States,...,$139,1.0,0.0,NaN,NaN,3.0,1.0,129.0,NaN,NaN
102571,6079735,Sunny 1BR on UES.,12171515616,verified,Vitaly,Manhattan,Upper East Side,40.77098,-73.95034,United States,...,$163,1.0,76.0,6/23/2019,1.61,2.0,1.0,79.0,NaN,NaN
102572,6080287,Bright spacious 1BR w high ceilings,39863828636,verified,James,Manhattan,Upper West Side,40.78550,-73.97642,United States,...,$127,1.0,0.0,NaN,NaN,3.0,1.0,380.0,NaN,NaN
102573,6080839,2BR apt. in converted church with large terrace,38845651458,verified,Annika,Brooklyn,Cobble Hill,40.68836,-73.99763,United States,...,$159,6.0,6.0,10/27/2018,0.13,5.0,1.0,89.0,NaN,NaN
102574,6081391,Couch or space in shared apartment,95400690951,unconfirmed,Lisa,Manhattan,East Village,40.72815,-73.97598,United States,...,$44,1.0,0.0,NaN,NaN,2.0,1.0,175.0,No Smoking No Pets No Parties No Loud Music,NaN
102575,6081944,NYC Chauncey 2 .20 min to manhattan,26326930315,verified,Michael,Brooklyn,Bedford-Stuyvesant,40.68237,-73.91977,United States,...,$120,1.0,123.0,3/17/2019,2.95,2.0,4.0,200.0,NO Smoking Pets Allowed with a $375 non refund...,NaN
102576,6082496,Quiet Bushwick Bedroom,70937504498,verified,Stonie,Brooklyn,Bushwick,40.69289,-73.92312,United States,...,$105,1.0,3.0,1/11/2017,0.06,2.0,1.0,225.0,NaN,NaN
102577,6083048,Gigantic Private Brooklyn Apartment,55330806381,verified,Nikki,Brooklyn,Greenpoint,40.72442,-73.93957,United States,...,$139,10.0,2.0,7/6/2016,0.04,1.0,1.0,33.0,NaN,NaN
102578,6083601,Sunny & Spacious near Central Park,41624631525,verified,Guida,Manhattan,East Harlem,40.79674,-73.94449,United States,...,$35,5.0,4.0,1/6/2016,0.08,1.0,1.0,323.0,NaN,NaN
102579,6084153,Alexander's 2BR Luxury Quarters,32736284559,verified,Juan,Brooklyn,Bedford-Stuyvesant,40.68740,-73.93830,United States,...,$59,3.0,123.0,6/26/2019,2.53,4.0,1.0,203.0,NaN,NaN
102580,6084705,"Near LGA, Citifield, US Open Tennis",97606085736,verified,Carmen,Queens,East Elmhurst,40.76578,-73.86424,United States,...,$122,1.0,209.0,6/11/2019,4.38,3.0,1.0,270.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
102581,6085258,Bright Bedroom in Bustling Bed Stuy Brooklyn,17339949163,unconfirmed,Amber,Brooklyn,Bedford-Stuyvesant,40.68742,-73.92825,United States,...,$15,2.0,34.0,7/1/2019,0.70,5.0,3.0,299.0,It is a residential building so all of the res...,NaN
102582,6085810,Private room in the best part of BK,4746552394,verified,Brad,Brooklyn,Crown Heights,40.66743,-73.94712,United States,...,$103,7.0,49.0,6/1/2019,1.01,2.0,1.0,425.0,No Smoking. Pets Allowed with fee.,NaN
102583,6086362,1 BR apartment sublet.,15723384490,verified,Tassili,Manhattan,Harlem,40.80594,-73.95363,United States,...,$49,5.0,0.0,NaN,NaN,2.0,1.0,327.0,* No smoking indoors. * No pets * No loud/la...,NaN
102584,6086914,2 block walk from the beach in NYC,70051719594,verified,Vladimir,Queens,Arverne,40.59270,-73.78990,United States,...,$113,2.0,89.0,5/26/2019,1.82,2.0,1.0,394.0,NaN,NaN
102585,6087467,Williamsburg family home -3 bedroom,23540078751,verified,Lou,Brooklyn,Williamsburg,40.71558,-73.93926,United States,...,$129,5.0,4.0,3/27/2016,0.08,5.0,1.0,157.0,* No smoking indoors. * No pets * No loud/la...,NaN
102586,6088019,Patio Oasis in Upper East Side,41141109074,verified,Margaret,Manhattan,Upper East Side,40.77703,-73.94773,United States,...,$42,4.0,8.0,8/8/2016,0.17,5.0,1.0,159.0,- NO SMOKING (You'll have to do that outside i...,NaN
102587,6088571,Adorable One-Bed in Williamsburg!,20914678851,verified,Taylor,Brooklyn,Williamsburg,40.71687,-73.94656,United States,...,$78,1.0,66.0,6/16/2019,1.35,2.0,1.0,352.0,• Check-in time is 2PM. Check-out time is 11am...,NaN
102588,6089124,"Loft Space for Events, Meetings & Shoots",85557432222,unconfirmed,Kalin,Manhattan,Flatiron District,40.74068,-73.98999,United States,...,$124,1.0,177.0,6/29/2019,3.78,4.0,1.0,410.0,Keep the apartment clean and damage free please.,NaN
102589,6089676,Lrg room 1 block from Prospect Park,74549151787,unconfirmed,Dave,Brooklyn,Flatbush,40.65231,-73.96189,United States,...,$61,3.0,0.0,NaN,NaN,1.0,1.0,200.0,House Rules 1. Check-in is 4 pm local time. If...,NaN
102590,6090228,Wonderful artists' loft in Brooklyn,9184535139,unconfirmed,Daniel,Brooklyn,Crown Heights,40.66673,-73.96127,United States,...,$50,1.0,0.0,NaN,NaN,1.0,1.0,276.0,#NAME?,NaN
102591,6090781,Columbus Ave Apt 1 block from Park,50908010324,verified,Lawrence,Manhattan,Upper West Side,40.77408,-73.98181,United States,...,$228,5.0,17.0,1/4/2019,0.35,5.0,1.0,134.0,#NAME?,NaN
102592,6091333,3BR/1 Ba in TriBeCa w/ outdoor deck,53266862889,unconfirmed,Nick,Manhattan,Tribeca,40.71845,-74.01183,United States,...,$157,1.0,0.0,NaN,NaN,2.0,1.0,177.0,Guests should treat my home as if it were thei...,NaN
102593,6091885,"Welcoming, Clean, Cheap on St Marks",33188605074,verified,Felipe,Manhattan,East Village,40.72826,-73.98422,United States,...,$220,1.0,8.0,9/6/2015,0.16,4.0,2.0,152.0,* No smoking indoors. * No pets * No loud/la...,NaN
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [8]:
df.head(3)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN

In [8]:
data.iloc[0,1]

'Clean & quiet apt home by the park'

In [10]:
data.loc[data['service fee']=='$193']

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, last review, reviews per month, review rate number, calculated host listings count, availability 365, house_rules, license]
Index: []

[0 rows x 26 columns]

In [12]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [13]:
data.info

<bound method DataFrame.info of              id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...  \
0                Kensington  40.64749 -73.97237  United States  ...
1                   Midtown  40.75362 -73.98377  United States  ...
2                    Harlem  40.80902 -73.94190  United States  ...
3              Clinton Hill  40.68514 -73.95976  United States  ...
4               East Harlem  40.79851 -73.94399  United States  ...
...                     ...       ...       ...            ...  ...
102594         Williamsburg  40.70862 -73.94651  United States  ...
102595  Morningside Heights  40.80460 -73.96545  United States  ...
102596           Park Slope  40.67505 -73.98045  United States  ...
102597     Long Island City  40.74989 -73.93777  United States  ...
102598      Upper West Side  40.76807 -73.98342  United States  ...

       service fee minimum nights number of reviews last review  \
0            $193            10.0               9.0  10/19/2021
1             $28            30.0              45.0   5/21/2022
2            $124             3.0               0.0         NaN
3             $74            30.0             270.0    7/5/2019
4             $41            10.0               9.0  11/19/2018
...            ...            ...               ...         ...
102594       $169             1.0               0.0         NaN
102595       $167             1.0               1.0    7/6/2015
102596       $198             3.0               0.0         NaN
102597       $109             2.0               5.0  10/11/2015
102598       $206             1.0               0.0         NaN

        reviews per month review rate number calculated host listings count  \
0                    0.21                4.0                            6.0
1                    0.38                4.0                            2.0
2                     NaN                5.0                            1.0
3                    4.64                4.0                            1.0
4                    0.10                3.0                            1.0
...                   ...                ...                            ...
102594                NaN                3.0                            1.0
102595               0.02                2.0                            2.0
102596                NaN                5.0                            1.0
102597               0.10                3.0                            1.0
102598                NaN                3.0                            1.0

        availability 365                                        house_rules  \
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

       license
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
102594     NaN
102595     NaN
102596     NaN
102597     NaN
102598     NaN

[102599 rows x 26 columns]>

In [14]:
data.info

<bound method DataFrame.info of              id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !
3       1002755                                               NaN
4       1003689  Entire Apt: Spacious Studio/Loft by central park
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
2       78829239556                    NaN        Elise           Manhattan
3       85098326012            unconfirmed        Garry            Brooklyn
4       92037596077               verified       Lyndon           Manhattan
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country  ...  \
0                Kensington  40.64749 -73.97237  United States  ...
1                   Midtown  40.75362 -73.98377  United States  ...
2                    Harlem  40.80902 -73.94190  United States  ...
3              Clinton Hill  40.68514 -73.95976  United States  ...
4               East Harlem  40.79851 -73.94399  United States  ...
...                     ...       ...       ...            ...  ...
102594         Williamsburg  40.70862 -73.94651  United States  ...
102595  Morningside Heights  40.80460 -73.96545  United States  ...
102596           Park Slope  40.67505 -73.98045  United States  ...
102597     Long Island City  40.74989 -73.93777  United States  ...
102598      Upper West Side  40.76807 -73.98342  United States  ...

       service fee minimum nights number of reviews last review  \
0            $193            10.0               9.0  10/19/2021
1             $28            30.0              45.0   5/21/2022
2            $124             3.0               0.0         NaN
3             $74            30.0             270.0    7/5/2019
4             $41            10.0               9.0  11/19/2018
...            ...            ...               ...         ...
102594       $169             1.0               0.0         NaN
102595       $167             1.0               1.0    7/6/2015
102596       $198             3.0               0.0         NaN
102597       $109             2.0               5.0  10/11/2015
102598       $206             1.0               0.0         NaN

        reviews per month review rate number calculated host listings count  \
0                    0.21                4.0                            6.0
1                    0.38                4.0                            2.0
2                     NaN                5.0                            1.0
3                    4.64                4.0                            1.0
4                    0.10                3.0                            1.0
...                   ...                ...                            ...
102594                NaN                3.0                            1.0
102595               0.02                2.0                            2.0
102596                NaN                5.0                            1.0
102597               0.10                3.0                            1.0
102598                NaN                3.0                            1.0

        availability 365                                        house_rules  \
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
2                  352.0  I encourage you to use my kitchen, cooking and...
3                  322.0                                                NaN
4                  289.0  Please no smoking in the house, porch or on th...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                                NaN
102597             386.0                                                NaN
102598              69.0                                                NaN

       license
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
102594     NaN
102595     NaN
102596     NaN
102597     NaN
102598     NaN

[102599 rows x 26 columns]>

In [15]:
data['license']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
102594    NaN
102595    NaN
102596    NaN
102597    NaN
102598    NaN
Name: license, Length: 102599, dtype: str

## Tasks to be carried out on the dataset
1. Deleting Redundant Columns
2. Dropping the Duplicates
3. Cleaning Individual Columns
4. Removing the Default NaN values from the DataSet
5. Check for some more Transformations

In [16]:
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [17]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [18]:
columns_to_keep=['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columns_to_drop=['id','reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

In [21]:
print(len(columns_to_keep))
print(len(columns_to_drop))

19
7

## 1st Method Filtering Data

In [22]:
dataframe=data[columns_to_keep]

In [23]:
dataframe.shape

(102599, 19)

In [24]:
data.drop(columns=columns_to_drop, inplace=True)

In [25]:
data.shape

(102599, 19)

In [26]:
data

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

## 2. Renaming Columns

In [27]:
data.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='str')

In [33]:
new_column_names=[]
count=0
for i in data.columns:
    new_column_names.append(i.lower())

In [36]:
print(len(new_column_names))

19

In [39]:
data.columns=new_column_names

In [40]:
data.columns

Index(['name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='str')

In [41]:
data

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN

## 3. Finding Duplicates

In [44]:
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102594     True
102595     True
102596     True
102597     True
102598     True
Length: 102599, dtype: bool

In [45]:
data.duplicated().head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [46]:
data.duplicated().tail()

102594    True
102595    True
102596    True
102597    True
102598    True
dtype: bool

In [47]:
data.duplicated().tail(30).sum()

np.int64(30)

In [48]:
data.drop_duplicates(inplace=True)

In [49]:
data.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
102053    False
102054    False
102055    False
102056    False
102057    False
Length: 102058, dtype: bool

In [50]:
data.shape

(102058, 19)

In [51]:
data.duplicated().sum()

np.int64(0)

## 3. Cleaning Individual Columns

In [52]:
data.isna()

,name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,construction year,price,service fee,minimum nights,number of reviews,last review
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
102054,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
102055,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False
102056,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,True
102057,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [53]:
data.isna().sum()

name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [54]:
data.dropna(inplace=True)

In [55]:
data.isna().sum()

name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
last review               0
dtype: int64